[package]
name = "fukuro"
version = "0.1.0"
description = "Manga CBZ batcher"
authors = ["you"]
edition = "2021"

[lib]
name = "fukuro_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
zip = "2"
walkdir = "2"
uuid = { version = "1", features = ["v4"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "gif", "webp"] }
rayon = "1"
fast_image_resize = "4"
reqwest = { version = "0.12", features = ["json"] }
notify = "6"
strsim = "0.11"
regex = "1"
tokio = { version = "1", features = ["sync"] }
